# Site settings
title: "Oltrematica Dev Team"
description: "Team di sviluppo specializzato in soluzioni digitali innovative"
baseurl: ""
url: "https://oltrematica.dev"
author: "Oltrematica"

# Build settings
markdown: kramdown
highlighter: rouge
permalink: /blog/:year/:month/:day/:title/
paginate: 6
paginate_path: "/page:num/"

# Exclude from processing
exclude:
  - Gemfile
  - Gemfile.lock
  - node_modules
  - vendor/bundle/
  - vendor/cache/
  - vendor/gems/
  - vendor/ruby/
  - AGENTS.md
  - README.md

# Jekyll plugins
plugins:
  - jekyll-paginate
  - jekyll-sitemap
  - jekyll-seo-tag
  - jekyll-feed

# SEO settings
lang: it
locale: it_IT
twitter:
  card: summary_large_image
  username: oltrematica
og_image: /assets/images/og-image.jpg

# Blog settings
blog:
  title: "Dev Blog"
  description: "Articoli, tutorial e insights dal team di sviluppo"

# Social links
social:
  github: https://github.com/oltrematica
  linkedin: https://linkedin.com/company/oltrematica

# Contact info
contact:
  email: devteam@oltrematica.it

# Collections
collections:
  posts:
    output: true
    permalink: /blog/:year/:month/:day/:title/

# Defaults
defaults:
  - scope:
      path: ""
      type: "posts"
    values:
      layout: "post"
      author: "Oltrematica Team"
      linkedin: "oltrematica"
  - scope:
      path: ""
    values:
      image: /assets/images/og-image.jpg
