- title: "Sviluppo Web"
  description: "Creiamo applicazioni web moderne, responsive e performanti utilizzando le tecnologie più avanzate."
  icon: '<path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M9.75 17L9 20l-1 1h8l-1-1-.75-3M3 13h18M5 17h14a2 2 0 002-2V5a2 2 0 00-2-2H5a2 2 0 00-2 2v10a2 2 0 002 2z"></path>'
  features:
    - "React, Vue.js, Angular"
    - "Node.js, Express"
    - "Progressive Web Apps (PWA)"

- title: "Backend Development"
  description: "Sviluppiamo API robuste e scalabili con le migliori pratiche di architettura software."
  icon: '<path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M5 12h14M5 12a2 2 0 01-2-2V6a2 2 0 012-2h14a2 2 0 012 2v4a2 2 0 01-2 2M5 12a2 2 0 00-2 2v4a2 2 0 002 2h14a2 2 0 002-2v-4a2 2 0 00-2-2m-2-4h.01M17 16h.01"></path>'
  features:
    - "RESTful & GraphQL API"
    - "Microservices Architecture"
    - "Database Design & Optimization"

- title: "Cloud & DevOps"
  description: "Implementiamo soluzioni cloud native e pipeline CI/CD per garantire deployment rapidi e affidabili."
  icon: '<path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M3 15a4 4 0 004 4h9a5 5 0 10-.1-9.999 5.002 5.002 0 10-9.78 2.096A4.001 4.001 0 003 15z"></path>'
  features:
    - "AWS, Google Cloud, Azure"
    - "Docker & Kubernetes"
    - "CI/CD Automation"

- title: "Mobile Development"
  description: "Realizziamo applicazioni mobile native e cross-platform per iOS e Android."
  icon: '<path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M12 18h.01M8 21h8a2 2 0 002-2V5a2 2 0 00-2-2H8a2 2 0 00-2 2v14a2 2 0 002 2z"></path>'
  features:
    - "React Native, Flutter"
    - "iOS & Android Native"
    - "App Store Optimization"

- title: "UI/UX Design"
  description: "Progettiamo interfacce intuitive e coinvolgenti che migliorano l'esperienza utente."
  icon: '<path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M7 21a4 4 0 01-4-4V5a2 2 0 012-2h4a2 2 0 012 2v12a4 4 0 01-4 4zm0 0h12a2 2 0 002-2v-4a2 2 0 00-2-2h-2.343M11 7.343l1.657-1.657a2 2 0 012.828 0l2.829 2.829a2 2 0 010 2.828l-8.486 8.485M7 17h.01"></path>'
  features:
    - "User Research & Testing"
    - "Wireframing & Prototyping"
    - "Design System Creation"

- title: "Consulenza Tecnica"
  description: "Offriamo consulenza specializzata per guidare le tue decisioni tecnologiche strategiche."
  icon: '<path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M9 12l2 2 4-4m5.618-4.016A11.955 11.955 0 0112 2.944a11.955 11.955 0 01-8.618 3.04A12.02 12.02 0 003 9c0 5.591 3.824 10.29 9 11.622 5.176-1.332 9-6.03 9-11.622 0-1.042-.133-2.052-.382-3.016z"></path>'
  features:
    - "Code Review & Audit"
    - "Architecture Planning"
    - "Technology Stack Selection"
